# Generated by Django 5.2.17 on 2026-09-23 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentChannelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('can_email', models.BooleanField(default=False)),
                ('can_buy_domains', models.BooleanField(default=False)),
                ('can_sms', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=False)),
                ('monthly_limit_cents', models.PositiveIntegerField(default=0)),
                ('max_domain_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_tlds', models.JSONField(blank=True, default=list)),
                ('auto_renew', models.BooleanField(default=False)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agent', models.CharField(blank=True, db_index=True, max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('verb', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, max_length=320)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=253, unique=True)),
                ('owner_agent', models.CharField(blank=True, max_length=255)),
                ('purchased', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('registering', 'Registering'), ('dns', 'Configuring DNS'), ('verifying', 'Verifying email'), ('ready', 'Ready'), ('failed', 'Failed'), ('action_required', 'Action required')], max_length=20)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('renewal_cents', models.PositiveIntegerField(default=0)),
                ('zone_id', models.CharField(blank=True, max_length=64)),
                ('email_domain_id', models.CharField(blank=True, max_length=128)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('warmup_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('address', models.CharField(max_length=320)),
                ('source', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'address'), name='channels_optout_once')],
            },
        ),
        migrations.CreateModel(
            name='SpendEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('amount_cents', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('reserved', 'Reserved'), ('charged', 'Charged'), ('released', 'Released')], default='reserved', max_length=10)),
                ('dedupe_key', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'dedupe_key'), name='channels_spend_once')],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('address', models.CharField(max_length=320, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_agent_channels.domain')),
                ('spend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_agent_channels.spendentry')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='spend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_agent_channels.spendentry'),
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('event_id', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='channels_webhook_once'), models.CheckConstraint(condition=models.Q(('event_id', ''), _negated=True), name='channels_webhook_event_id')],
            },
        ),
        migrations.CreateModel(
            name='ExternalMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('status', models.CharField(choices=[('pending_approval', 'Awaiting approval'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('received', 'Received'), ('rejected', 'Rejected')], max_length=20)),
                ('counterparty', models.CharField(max_length=320)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body', models.TextField(blank=True)),
                ('thread_ref', models.CharField(blank=True, max_length=256)),
                ('in_reply_to', models.CharField(blank=True, max_length=256)),
                ('provider_message_id', models.CharField(blank=True, max_length=256)),
                ('dedupe_key', models.CharField(max_length=256)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_agent_channels.endpoint')),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', 'direction', 'created_at'], name='django_agen_endpoin_d9d43d_idx'), models.Index(fields=['provider_message_id'], name='django_agen_provide_f64f87_idx')],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'direction', 'dedupe_key'), name='channels_message_dedupe')],
            },
        ),
    ]
