# Generated by Django 5.2.17 on 2026-09-23 22:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('direct', 'Direct')], max_length=10)),
                ('name', models.SlugField(blank=True, max_length=80)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('direct_key', models.CharField(blank=True, max_length=64)),
                ('last_seq', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('is_paused', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('key_digest', models.CharField(max_length=64)),
                ('command', models.CharField(max_length=60)),
                ('payload_digest', models.CharField(max_length=64)),
                ('result_type', models.CharField(max_length=40)),
                ('result_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'key_digest'), name='workspace_receipt_once')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveBigIntegerField()),
                ('author', models.CharField(max_length=255)),
                ('author_is_agent', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_agent_workspace.channel')),
                ('thread_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='django_agent_workspace.message')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(choices=[('mention', 'Mention'), ('direct', 'Direct message'), ('reply', 'Thread reply')], max_length=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_agent_workspace.message')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('member', 'Member'), ('manager', 'Manager')], max_length=10)),
                ('handle', models.SlugField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='django_agent_workspace.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='django_agent_workspace.workspace'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('verb', models.CharField(max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='django_agent_workspace.workspace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('principal', models.CharField(max_length=255)),
                ('last_read_seq', models.PositiveBigIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='django_agent_workspace.channel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'principal'), name='workspace_channel_member_once')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', 'created_at'], name='django_agen_author_7da8ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('channel', 'seq'), name='workspace_message_seq_unique'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['recipient', 'read_at', '-id'], name='django_agen_recipie_b36cff_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(fields=('recipient', 'message'), name='workspace_inbox_once'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'principal'), name='workspace_member_once'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'handle'), name='workspace_handle_unique'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'direct'), _negated=True), fields=('workspace', 'name'), name='workspace_channel_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'direct')), fields=('workspace', 'direct_key'), name='workspace_direct_pair_unique'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['workspace', '-id'], name='django_agen_workspa_34f014_idx'),
        ),
    ]
