# Generated by Django 5.2.17 on 2026-09-08 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profilegrant_user_kind'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='crm.charity'),
        ),
        migrations.AddField(
            model_name='profilegrant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profilegrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['charity', 'is_active'], name='accounts_pr_charity_c080d3_idx'),
        ),
        migrations.AddIndex(
            model_name='profilegrant',
            index=models.Index(fields=['user', 'is_active'], name='accounts_pr_user_id_e42e8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilegrant',
            constraint=models.UniqueConstraint(fields=('user', 'profile'), name='accounts_unique_profile_grant'),
        ),
    ]
