"""Opt-in model-list isolation proof; never emit credentials or response bodies.

Run from the repository root with GATEWAY_MODEL_CONTAINER_TESTS=1 and
.venv/bin/python -m unittest discover -s infrastructure/ai-gateway/tests
-p test_model_discovery.py -v (use unittest, not pytest --showlocals).
All images must already be local; nothing is pulled. Optionally select a local
Python 3.11+ image with GATEWAY_MODEL_PYTHON_IMAGE (otherwise local IDs are probed).

Source inspected: transports/v2.2.1, commit
6493abd3d1422c9bfde95f242fd57b38e73ce881: handlers/{inference,providers,
provider_keys,governance}.go, lib/ctx.go, core/bifrost.go. Source is not
runtime evidence. All output below is generated by actual HTTP requests.
No production configuration is changed, even if this test succeeds.
"""

from contextlib import ExitStack, contextmanager
import base64
import gzip
from http.cookies import SimpleCookie
import http.client
import importlib.util
from io import StringIO
import json
import os
from pathlib import Path
import re
import secrets
import subprocess
import sys
import tempfile
import time
import unittest
from unittest import mock

from test_containers import docker
from test_policy import ROOT, image_pins


PIN = "maximhq/bifrost@sha256:a8942692af7b4b89196cd8fc33653b7353488dfd58b24078fe793b8574a8084b"
PROVIDERS = {"isolation-alpha": ("alpha-one", "alpha-two"),
             "isolation-beta": ("beta-one", "beta-two")}
MAX_BODY = 2 * 1024 * 1024
EDGE_ERRORS = {400: {"error": {"message": "Bad request"}},
               401: {"error": {"message": "Virtual key required"}},
               403: {"error": {"message": "Catalog access denied"}}}
_REQUEST_CONTAINER = None
# Fixed argv contains no request data. Unlike BusyBox nc, HTTPConnection keeps
# the socket open after stdin EOF while Caddy awaits asynchronous upstream work.
_HTTP_REQUEST_SCRIPT = """
import base64
import http.client
import json
import logging
import sys

logging.disable(logging.CRITICAL)
sys.tracebacklimit = 0
try:
    request = json.load(sys.stdin)
    body = None if request["payload"] is None else json.dumps(request["payload"]).encode("utf-8")
    connection = http.client.HTTPConnection("127.0.0.1", request["port"], timeout=request["timeout"])
    connection.set_debuglevel(0)
    try:
        connection.request(request["method"], request["path"], body=body, headers=request["headers"])
        with connection.getresponse() as response:
            result = {"status": response.status,
                      "body": base64.b64encode(response.read(%d + 1)).decode("ascii"),
                      "headers": response.getheaders()}
    finally:
        connection.close()
    sys.stdout.write(json.dumps(result))
except BaseException:
    sys.stdout.write('{"error":"Local test HTTP request failed"}')
    sys.exit(1)
""" % MAX_BODY


@contextmanager
def container_transport(container):
    """Scope all requests to the disposable fixture, including on test failure."""
    global _REQUEST_CONTAINER
    previous = _REQUEST_CONTAINER
    _REQUEST_CONTAINER = container
    try:
        yield
    finally:
        _REQUEST_CONTAINER = previous


def request(port, path, method="GET", headers=None, payload=None, *, timeout=45):
    """Keep credentials on stdin and response bytes in memory, never in diagnostics."""
    if _REQUEST_CONTAINER is None:
        raise RuntimeError("Isolated test HTTP transport is not configured")
    try:
        fields = {"Content-Type": "application/json", "Accept": "application/json",
                  "Accept-Encoding": "identity", **(headers or {})}
        result = subprocess.run(
            ["docker", "exec", "-i", _REQUEST_CONTAINER, "python3", "-I", "-c", _HTTP_REQUEST_SCRIPT],
            input=json.dumps({"port": port, "path": path, "method": method, "headers": fields,
                              "payload": payload, "timeout": timeout}).encode("utf-8"),
            capture_output=True, timeout=timeout + 2)
        if result.returncode:
            raise RuntimeError("Isolated test HTTP transport failed")
        response = json.loads(result.stdout)
        if not isinstance(response, dict) or type(response.get("status")) is not int:
            raise ValueError
        body = base64.b64decode(response["body"], validate=True)
        if len(body) > MAX_BODY:
            raise RuntimeError("HTTP response exceeded test size limit")
        response_headers = response["headers"]
        if not isinstance(response_headers, list) or any(
                not isinstance(pair, list) or len(pair) != 2 or
                not all(isinstance(value, str) for value in pair) for pair in response_headers):
            raise ValueError
        return response["status"], body, [tuple(pair) for pair in response_headers]
    except (OSError, subprocess.TimeoutExpired, UnicodeError, ValueError, TypeError, KeyError):
        raise RuntimeError("Local test HTTP request failed") from None


def status(port, path):
    """Readiness returns only a safe status and uses the same internal transport."""
    try:
        return request(port, path, timeout=2)[0]
    except RuntimeError:
        return 0


def json_object(body):
    try:
        document = json.loads(body)
    except (ValueError, UnicodeError):
        raise RuntimeError("Expected a JSON response") from None
    if not isinstance(document, dict):
        raise RuntimeError("Expected a JSON object response")
    return document


def model_observation(code, body, headers, allowed, provider_keys, private_values):
    """Project untrusted data to numeric observations; no raw value leaves this helper."""
    try:
        document = json.loads(body)
    except (ValueError, UnicodeError):
        document = None
    is_object = isinstance(document, dict)
    document = document if is_object else {}
    data = document.get("data")
    rows = data if isinstance(data, list) else []
    ids = [row["id"] for row in rows if isinstance(row, dict) and isinstance(row.get("id"), str)]
    expected = set(allowed)
    allowed_providers = {model.split("/", 1)[0] for model in expected}
    forbidden = set(provider_keys.values())
    for provider, models in PROVIDERS.items():
        forbidden.update(model for model in models if provider + "/" + model not in expected)
        if provider not in allowed_providers:
            forbidden.add(provider)
    wire = body.decode("utf-8", errors="replace") + json.dumps(headers)

    def field_count(value, names):
        if isinstance(value, dict):
            return sum(int(key in names) + field_count(item, names)
                       for key, item in value.items())
        if isinstance(value, list):
            return sum(field_count(item, names) for item in value)
        return 0

    projected = {"object": "list", "data": [
        {"id": model, "object": "model", "owned_by": model.split("/", 1)[0]}
        for model in sorted(expected)
    ]}
    exact_projection = False
    if isinstance(data, list) and len(ids) == len(rows):
        exact_projection = {**document, "data": sorted(rows, key=lambda row: row["id"])} == projected
    types = [value.split(";", 1)[0].strip().lower() for name, value in headers
             if name.lower() == "content-type"]
    encodings = [value.strip().lower() for name, value in headers if name.lower() == "content-encoding"]
    return {"status": code, "models": len(rows), "providers": len({model.split("/", 1)[0] for model in ids}),
            "unexpected_models": sum(model not in expected for model in ids),
            "missing_models": len(expected - set(ids)), "malformed_rows": len(rows) - len(ids),
            "duplicate_ids": len(ids) - len(set(ids)), "json_object": int(is_object),
            "json_content_type": int(types == ["application/json"]),
            "encoded_body": int(bool(encodings) and encodings != ["identity"]),
            "gzip_magic": int(body.startswith(b"\x1f\x8b")), "body_bytes": len(body),
            "data_array": int(isinstance(data, list)),
            "key_status_fields": field_count(document, {"key_statuses"}),
            "error_fields": field_count(document, {"error", "errors"}),
            "exact_projection": int(exact_projection),
            "exact_error": int(code in EDGE_ERRORS and document == EDGE_ERRORS[code]),
            "forbidden_metadata": sum(marker in wire for marker in forbidden),
            "credential_hits": sum(value in wire for value in private_values)}


class ObservationTests(unittest.TestCase):
    """Default-path unit coverage of the reporter; no Docker or provider access."""

    def test_empty_success_is_distinct_from_an_error(self):
        empty = model_observation(200, b'{"data": []}', [], (), {}, ())
        denied = model_observation(401, b'{"error": {"message": "denied"}}', [], (), {}, ())
        self.assertEqual((empty["models"], empty["error_fields"], empty["data_array"]), (0, 0, 1))
        self.assertEqual((denied["models"], denied["error_fields"], denied["data_array"]), (0, 1, 0))

    def test_scoped_models_and_metadata_outside_data(self):
        body = json.dumps({"data": [{"id": "isolation-alpha/alpha-one"}],
                           "key_statuses": [{"provider": "isolation-beta", "error": "denied"}]}).encode()
        result = model_observation(200, body, [], ("isolation-alpha/alpha-one",), {}, ())
        self.assertEqual((result["unexpected_models"], result["missing_models"]), (0, 0))
        self.assertEqual((result["forbidden_metadata"], result["key_status_fields"], result["error_fields"]), (1, 1, 1))
        self.assertEqual(result["exact_projection"], 0)

    def test_credential_echo_is_reported_only_as_a_count(self):
        value = secrets.token_urlsafe(32)
        result = model_observation(200, json.dumps({"data": [], "extra": value}).encode(), [], (), {}, (value,))
        self.assertEqual(result["credential_hits"], 1)
        self.assertTrue(all(isinstance(count, int) for count in result.values()))
        result = model_observation(401, b'{}', [("X-Debug", value)], (), {}, (value,))
        self.assertEqual(result["credential_hits"], 1)

    def test_malformed_and_duplicate_rows_cannot_look_like_scoped_success(self):
        body = b'{"data": [null, {"id": 42}, {"id": "isolation-alpha/alpha-one"}, {"id": "isolation-alpha/alpha-one"}]}'
        result = model_observation(200, body, [], ("isolation-alpha/alpha-one",), {}, ())
        self.assertEqual((result["malformed_rows"], result["models"], result["duplicate_ids"]), (2, 4, 1))
        self.assertEqual(result["exact_projection"], 0)

    def test_exact_projection_rejects_extra_metadata_even_in_allowed_scope(self):
        row = {"id": "isolation-alpha/alpha-one", "object": "model", "owned_by": "isolation-alpha"}
        for extra, expected in (({}, 1), ({"created": 1}, 0), ({"key_statuses": []}, 0)):
            result = model_observation(200, json.dumps({"object": "list", "data": [{**row, **extra}]}).encode(),
                                       [], (row["id"],), {}, ())
            self.assertEqual(result["exact_projection"], expected)

    def test_identity_check_rejects_equal_size_wrong_scope(self):
        result = model_observation(200, b'{"data":[{"id":"isolation-beta/beta-one"}]}', [],
                                   ("isolation-alpha/alpha-one",), {}, ())
        self.assertEqual((result["unexpected_models"], result["missing_models"]), (1, 1))

    def test_exact_projection_accepts_multi_provider_rows_in_any_order(self):
        ids = ("isolation-beta/beta-one", "isolation-alpha/alpha-two")
        rows = [{"id": value, "object": "model", "owned_by": value.split("/")[0]} for value in ids]
        result = model_observation(200, json.dumps({"object": "list", "data": rows}).encode(), [], ids, {}, ())
        self.assertEqual((result["exact_projection"], result["providers"]), (1, 2))

    def test_only_exact_static_error_is_accepted(self):
        for code, document in EDGE_ERRORS.items():
            result = model_observation(code, json.dumps(document).encode(), [], (), {}, ())
            self.assertEqual(result["exact_error"], 1)
            result = model_observation(code, json.dumps({**document, "key_statuses": []}).encode(), [], (), {}, ())
            self.assertEqual((result["exact_error"], result["key_status_fields"]), (0, 1))

    def test_non_json_and_compressed_successes_are_diagnosed_as_counts(self):
        for body, headers, encoded, magic in ((b"not JSON", [], 0, 0),
                (gzip.compress(b'{"data":[]}'), [("Content-Encoding", "gzip")], 1, 1)):
            result = model_observation(200, body, headers, (), {}, ())
            self.assertEqual((result["json_object"], result["data_array"], result["exact_projection"]), (0, 0, 0))
            self.assertEqual((result["encoded_body"], result["gzip_magic"]), (encoded, magic))
            self.assertTrue(all(type(count) is int for count in result.values()))

    def test_scoped_provider_key_ids_are_metadata_not_public_catalog(self):
        value = secrets.token_urlsafe(32)
        body = json.dumps({"data": [], "extra_fields": {"key_statuses": [{"key_id": value}]}}).encode()
        result = model_observation(200, body, [], ("isolation-alpha/alpha-one",), {"isolation-alpha": value}, ())
        self.assertEqual((result["forbidden_metadata"], result["key_status_fields"]), (1, 1))

    def test_transport_requests_identity_and_keeps_credentials_on_stdin(self):
        value = secrets.token_urlsafe(32)
        body = json.dumps({"private": value}).encode()
        headers = [("Content-Type", "application/json"), ("Set-Cookie", value)]
        wire = json.dumps({"status": 200, "body": base64.b64encode(body).decode("ascii"),
                           "headers": headers}).encode()
        with container_transport("disposable-guard"), mock.patch.object(subprocess, "run") as run:
            run.return_value = subprocess.CompletedProcess([], 0, wire, b"")
            code, received, response_headers = request(9080, "/v1/models", "POST",
                headers={"Authorization": "Bearer " + value}, payload={"private": value}, timeout=7)
            self.assertEqual(code, 200)
            self.assertTrue(received == body and response_headers == headers)
            arguments, options = run.call_args
            self.assertTrue(arguments[0] == ["docker", "exec", "-i", "disposable-guard",
                                            "python3", "-I", "-c", _HTTP_REQUEST_SCRIPT])
            self.assertFalse(any(value in arg for arg in arguments[0]))
            sent = json.loads(options["input"])
            self.assertTrue(sent == {"port": 9080, "path": "/v1/models", "method": "POST",
                "headers": {"Content-Type": "application/json", "Accept": "application/json",
                            "Accept-Encoding": "identity", "Authorization": "Bearer " + value},
                "payload": {"private": value}, "timeout": 7})
            self.assertTrue(value.encode() in options["input"])
            self.assertTrue(options["capture_output"])
            self.assertEqual(options["timeout"], 9)

    def test_container_client_reads_response_before_closing(self):
        document = {"port": 9080, "path": "/v1/models", "method": "GET",
                    "headers": {"Accept-Encoding": "identity"}, "payload": None, "timeout": 7}
        output = StringIO()
        with mock.patch.object(http.client, "HTTPConnection") as client, \
                mock.patch.object(sys, "stdin", StringIO(json.dumps(document))), \
                mock.patch.object(sys, "stdout", output), \
                mock.patch.object(sys, "tracebacklimit", 0, create=True), \
                mock.patch("logging.disable"):
            connection = client.return_value
            response = connection.getresponse.return_value.__enter__.return_value
            response.status = 200
            response.getheaders.return_value = [("Content-Type", "application/json")]

            def read(limit):
                connection.close.assert_not_called()
                self.assertEqual(limit, MAX_BODY + 1)
                return b'{"data":[]}'

            response.read.side_effect = read
            exec(_HTTP_REQUEST_SCRIPT, {})
            client.assert_called_once_with("127.0.0.1", 9080, timeout=7)
            connection.request.assert_called_once_with("GET", "/v1/models", body=None,
                                                       headers=document["headers"])
            response.read.assert_called_once_with(MAX_BODY + 1)
            connection.close.assert_called_once_with()
        self.assertEqual(json.loads(output.getvalue()), {"status": 200,
            "body": base64.b64encode(b'{"data":[]}').decode("ascii"),
            "headers": [["Content-Type", "application/json"]]})

    def test_container_client_errors_have_no_raw_diagnostics(self):
        value = secrets.token_urlsafe(32)
        document = {"port": 9080, "path": "/v1/models", "method": "GET",
                    "headers": {}, "payload": None, "timeout": 7}
        output, errors = StringIO(), StringIO()
        with mock.patch.object(http.client, "HTTPConnection") as client, \
                mock.patch.object(sys, "stdin", StringIO(json.dumps(document))), \
                mock.patch.object(sys, "stdout", output), mock.patch.object(sys, "stderr", errors), \
                mock.patch.object(sys, "tracebacklimit", 0, create=True), \
                mock.patch("logging.disable"):
            client.return_value.getresponse.side_effect = OSError(value)
            with self.assertRaises(SystemExit) as caught:
                exec(_HTTP_REQUEST_SCRIPT, {})
            self.assertEqual(caught.exception.code, 1)
            client.return_value.close.assert_called_once_with()
        self.assertTrue(output.getvalue() == '{"error":"Local test HTTP request failed"}')
        self.assertTrue(errors.getvalue() == "")

    def test_transport_errors_are_fixed_and_responses_are_bounded(self):
        value = secrets.token_urlsafe(32)
        oversized = json.dumps({"status": 200, "body": base64.b64encode(b"x" * (MAX_BODY + 1)).decode("ascii"),
                                "headers": []}).encode()
        for returncode, stdout, message in (
                (1, value.encode(), "Isolated test HTTP transport failed"),
                (0, value.encode(), "Local test HTTP request failed"),
                (0, oversized, "HTTP response exceeded test size limit")):
            with self.subTest(returncode=returncode, response_bytes=len(stdout)), \
                    container_transport("disposable-guard"), mock.patch.object(subprocess, "run") as run:
                run.return_value = subprocess.CompletedProcess([], returncode, stdout, value.encode())
                with self.assertRaises(RuntimeError) as caught:
                    request(9080, "/v1/models")
                self.assertTrue(str(caught.exception) == message)

    def test_stored_key_id_is_authoritative_with_legacy_id_fallback(self):
        proof = ModelDiscoveryTests("test_pinned_model_discovery_isolation")
        expected, other = secrets.token_urlsafe(32), secrets.token_urlsafe(32)
        proof.provider_keys = {"isolation-alpha": expected}
        proof.private_values = []
        created = {"virtual_key": {"id": "fixture-vk", "value": "sk-bf-" + secrets.token_urlsafe(32)}}
        for key, accepted in (({"key_id": expected, "id": other}, True),
                              ({"id": expected}, True),
                              ({"key_id": other, "id": expected}, False)):
            stored = {"virtual_key": {"is_active": True, "allow_all_providers": False,
                "provider_configs": [{"provider": "isolation-alpha", "allowed_models": ["alpha-one"],
                                      "allow_all_keys": False, "keys": [key]}]}}
            with self.subTest(accepted=accepted, association_field="key_id" in key), \
                    mock.patch.object(proof, "api", side_effect=[created, stored]):
                if accepted:
                    proof.virtual_key("fixture", (("isolation-alpha", ("alpha-one",)),))
                else:
                    with self.assertRaisesRegex(AssertionError, "Stored provider key identity"):
                        proof.virtual_key("fixture", (("isolation-alpha", ("alpha-one",)),))


def fixture_caddy(root):
    """Exercise the actual production route, adding only local provider mocks."""
    rendered = (ROOT / "runtime/Caddyfile").read_text()
    if "reverse_proxy 127.0.0.1:9092" not in rendered:
        raise RuntimeError("Production Caddy model-catalog guard route is required")
    for port, (provider, models) in enumerate(PROVIDERS.items(), 9101):
        body = json.dumps({"object": "list", "data": [
            {"id": model, "object": "model", "created": 1, "owned_by": provider}
            for model in models
        ]})
        # Named synthetic-provider exception: local deterministic model catalogs,
        # no real provider/API traffic. Exact VK identities are verified below.
        # These listeners exist only until the disposable fixture is removed.
        rendered += (f'\nhttp://:{port} {{\n\tbind 127.0.0.1\n'
                     '\theader Content-Type application/json\n'
                     f'\trespond /v1/models `{body}` 200\n\trespond 404\n}}\n')
    path = root / "Caddyfile"
    path.write_text(rendered)
    return path


def local_python_image():
    """Inspect/probe local images only, never output image config or pull anything."""
    selected = os.environ.get("GATEWAY_MODEL_PYTHON_IMAGE")
    candidates = [selected] if selected else sorted(set(docker("images", "--quiet", "--no-trunc").split()))
    for candidate in candidates:
        try:
            identifier = docker("image", "inspect", "--format={{.Id}}", candidate).strip()
            if not re.fullmatch(r"sha256:[a-f0-9]{64}", identifier):
                continue
            # No namespace sharing or fixture secrets during interpreter discovery.
            # Override entrypoint, user and networking; discard all captured output.
            docker("run", "--rm", "--pull=never", "--network=none", "--read-only",
                   "--cap-drop=ALL", "--security-opt=no-new-privileges:true", "--log-driver=none",
                   "--user=65534:65534", "--memory=128m", "--pids-limit=32", "--entrypoint=python3",
                   identifier, "-I", "-S", "-B", "-c",
                   "import http.client, http.server, json, re, sys, threading; assert sys.version_info >= (3, 11)")
        except RuntimeError:
            continue
        return identifier
    raise RuntimeError("No local Python 3.11+ image is usable; select GATEWAY_MODEL_PYTHON_IMAGE (no images pulled)")


@unittest.skipUnless(os.environ.get("GATEWAY_MODEL_CONTAINER_TESTS") == "1",
                     "Opt-in isolated Docker model-discovery proof")
class ModelDiscoveryTests(unittest.TestCase):
    def api(self, path, method="GET", payload=None):
        code, body, _ = request(self.backend, path, method, self.admin, payload)
        self.assertIn(code, (200, 201), "Management API status")
        return json_object(body)

    def virtual_key(self, name, grants=()):
        # Empty grants deliberately inherit deny-by-default; never allow-all.
        result = self.api("/api/governance/virtual-keys", "POST", {
            "name": name, "provider_configs": [
                {"provider": provider, "allowed_models": list(models),
                 "key_ids": [self.provider_keys[provider]]}
                for provider, models in grants
            ],
        }).get("virtual_key", {})
        self.assertTrue(isinstance(result, dict), "VK response shape")
        value, identifier = result.get("value"), result.get("id")
        self.assertTrue(isinstance(value, str) and bool(re.fullmatch(r"sk-bf-[A-Za-z0-9_-]+", value)),
                        "Generated VK must match the edge token format")
        self.assertTrue(isinstance(identifier, str) and bool(re.fullmatch(r"[A-Za-z0-9_-]+", identifier)),
                        "Generated VK must have a safe resource ID")
        self.private_values.append(value)
        stored = self.api("/api/governance/virtual-keys/" + identifier).get("virtual_key", {})
        self.assertTrue(stored.get("is_active") is True, "Stored VK must be active")
        self.assertTrue(stored.get("allow_all_providers") is False, "Stored VK must not allow all providers")
        configs = stored.get("provider_configs") or []
        self.assertEqual(len(configs), len(grants))
        self.assertTrue({config.get("provider") for config in configs} == {provider for provider, _ in grants},
                        "Stored provider identities")
        for provider, models in grants:
            config = next(config for config in configs if config.get("provider") == provider)
            self.assertTrue(set(config.get("allowed_models") or []) == set(models), "Stored model grant")
            self.assertTrue(config.get("allow_all_keys") is False, "Stored provider key grant")
            self.assertEqual(len(config.get("keys") or []), 1, "Stored grant must bind one provider key")
            key = config["keys"][0]
            self.assertTrue(key.get("key_id", key.get("id")) == self.provider_keys[provider],
                            "Stored provider key identity")
        return identifier, {"Authorization": "Bearer " + value}

    def revoke(self, identifier):
        self.api("/api/governance/virtual-keys/" + identifier, "PUT", {"is_active": False})
        stored = self.api("/api/governance/virtual-keys/" + identifier).get("virtual_key", {})
        self.assertTrue(stored.get("is_active") is False, "Stored VK must be revoked")

    def observe(self, label, port, headers, allowed, path):
        """Never let raw responses/errors become unittest assertion operands."""
        code, body, response_headers = request(port, path, headers=headers)
        counts = model_observation(code, body, response_headers, allowed,
                                   self.provider_keys, self.private_values)
        print(json.dumps({"case": label, **counts}, sort_keys=True), flush=True)
        self.assertEqual(counts["credential_hits"], 0, "Response must not echo credentials")
        self.assertEqual(counts["json_object"], 1, "Response must be a JSON object")
        self.assertEqual(counts["json_content_type"], 1, "Response must declare JSON")
        self.assertEqual(counts["encoded_body"], 0, "Identity transport must not return compressed bytes")
        return counts

    def assert_identities(self, counts, allowed):
        self.assertEqual(counts["models"], len(allowed), "Exact scoped model count")
        self.assertEqual(counts["malformed_rows"] + counts["duplicate_ids"], 0, "Unique string model IDs")
        self.assertEqual(counts["unexpected_models"] + counts["missing_models"], 0, "Exact scoped model identities")

    def raw_probe(self, label, headers, allowed=(), *, code=200, quirk):
        """Pinned backend characterization, NOT public-edge authorization success.

        Explicit exceptions: empty deployment returns 200 [] even for invalid or
        revoked keys; configured errors disclose provider diagnostics; successful
        VK data is scoped but key_statuses is not safe public response metadata.
        Keep these assertions independent of (and weaker ONLY here than) the edge.
        """
        with self.subTest(raw_backend=label):
            counts = self.observe("raw/" + label, self.backend, headers, allowed, "/v1/models")
            self.assertEqual(counts["status"], code, "Pinned raw-backend characterization status")
            self.assert_identities(counts, allowed)
            if code == 200:
                self.assertEqual(counts["data_array"], 1)
            if quirk == "empty-auth-bypass":
                self.assertEqual(counts["models"], 0, "Empty raw success is NOT evidence of authentication")
            elif quirk == "denial-metadata":
                self.assertGreater(counts["forbidden_metadata"], 0, "Pinned denial exposes provider metadata")
            elif quirk == "scoped-data-with-diagnostics":
                self.assertGreater(counts["key_status_fields"], 0, "Pinned scoped catalog includes key diagnostics")
            else:
                self.fail("Unknown raw-backend characterization")

    def edge_probe(self, label, headers, allowed=(), *, path="/v1/models", code=200):
        """Strict exact projection/error contract; raw-backend quirks never pass here."""
        with self.subTest(case=label):
            counts = self.observe("edge/" + label, self.edge, headers, allowed, path)
            self.assertEqual(counts["forbidden_metadata"], 0, "Response must not disclose another scope")
            self.assertEqual(counts["key_status_fields"], 0, "Key diagnostics must be stripped entirely")
            self.assertEqual(counts["status"], code, "Exact guarded-edge status")
            self.assert_identities(counts, allowed)
            if code == 200:
                self.assertGreater(len(allowed), 0, "Empty catalogs must never be an edge success")
                self.assertEqual(counts["exact_projection"], 1, "Only the exact public catalog may be returned")
                self.assertEqual(counts["error_fields"], 0, "No backend errors may survive projection")
            else:
                self.assertEqual(counts["exact_error"], 1, "Only the exact static guard error may be returned")

    def test_pinned_model_discovery_isolation(self):
        pins = image_pins()
        self.assertEqual(pins["bifrost"], PIN, "Re-review source before changing the proof image")
        for image in pins.values():
            docker("image", "inspect", "--format={{.Id}}", image)
        python_image = local_python_image()
        self.provider_keys = {}
        self.private_values = []
        with tempfile.TemporaryDirectory(prefix="gateway-model-proof-", dir="/tmp") as temporary, ExitStack() as cleanup:
            root = Path(temporary)
            spec = importlib.util.spec_from_file_location("model_proof_secrets", ROOT / "runtime/fetch-secrets.py")
            helper = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(helper)
            credentials = {key: secrets.token_urlsafe(32) for key in helper.KEYS}
            self.private_values.extend(credentials.values())
            env = root / "private/bootstrap.env"
            helper.write_env(credentials, env)
            self.assertEqual(env.stat().st_mode & 0o777, 0o600)
            data = root / "data"
            data.mkdir()
            config = data / "config.json"
            config.write_bytes((ROOT / "runtime/config.json").read_bytes())
            # Same disposable UID/bind-mount exception as test_containers.py.
            # Private temp parent remains 0700; all files are removed on exit.
            data.chmod(0o777)
            config.chmod(0o666)
            caddy_config = fixture_caddy(root)
            network, bifrost, caddy, guard = ("gateway-model-proof-" + secrets.token_hex(12) for _ in range(4))
            # No external traffic during discovery probes. Bifrost startup needs
            # its public catalog download before opening the listener; temporarily
            # attach the default bridge ONLY before any provider keys are created.
            docker("network", "create", "--internal", network)
            cleanup.callback(docker, "network", "rm", network)
            self.assertEqual(docker("network", "inspect", "--format={{.Internal}}", network).strip(), "true")
            hardened = ("--read-only", "--cap-drop=ALL", "--security-opt=no-new-privileges:true", "--log-driver=none")
            # Requests run inside the shared namespace; no ports reach the host.
            # Register before run: Docker may create a stopped container even if
            # startup fails. Cleanup targets only these random fixture names.
            cleanup.callback(docker, "rm", "-f", bifrost)
            docker("run", "-d", "--pull=never", "--name", bifrost, *hardened, "--network", network,
                   "--user=1000:1000", "--memory=2560m", "--pids-limit=256",
                   "--tmpfs=/tmp:size=64m,mode=1777", "--env-file", str(env),
                   "-e", "APP_HOST=127.0.0.1", "-e", "APP_PORT=8080", "-e", "APP_DIR=/app/data",
                   "-e", "LOG_LEVEL=warn", "-e", "GOMEMLIMIT=2300MiB", "-v", f"{data}:/app/data",
                   pins["bifrost"])
            docker("network", "connect", "bridge", bifrost)
            cleanup.callback(docker, "rm", "-f", caddy)
            docker("run", "-d", "--pull=never", "--name", caddy, *hardened, "--network", "container:" + bifrost,
                   "--cap-add=NET_BIND_SERVICE", "--tmpfs=/tmp", "--tmpfs=/data", "--tmpfs=/config",
                   "--memory=256m", "-e", "GATEWAY_DOMAIN=http://:9080",
                   "-v", f"{caddy_config}:/etc/caddy/Caddyfile:ro", pins["caddy"])
            cleanup.callback(docker, "rm", "-f", guard)
            # Named packaging-only exception: a pre-existing local Python image
            # supplies stdlib instead of the production host interpreter. Execute
            # the unchanged runtime file with its real fixed 9092 -> 8080 ports.
            # No auth/fetch mocks or admin credentials; remove with this fixture.
            docker("run", "-d", "--pull=never", "--name", guard, *hardened,
                   "--network", "container:" + bifrost, "--user=65534:65534",
                   "--memory=128m", "--pids-limit=32", "--entrypoint=python3",
                   "-v", f"{ROOT}/runtime/model-catalog.py:/model-catalog.py:ro",
                   python_image, "-I", "-S", "-B", "/model-catalog.py")
            # Readiness and all probes use the same Python HTTP client inside
            # the disposable guard, never nc or host-published ports.
            cleanup.enter_context(container_transport(guard))
            self.backend, self.edge = 8080, 9080
            deadline = time.monotonic() + 120
            while time.monotonic() < deadline:
                if status(self.backend, "/health") == 200 and status(self.edge, "/healthz") == 200:
                    break
                time.sleep(0.5)
            else:
                self.fail("Isolated gateway readiness timed out")
            docker("network", "disconnect", "bridge", bifrost)
            # Inspect only names, never Docker Config.Env or other credential state.
            networks = docker("inspect", "--format={{range $name, $value := .NetworkSettings.Networks}}{{$name}} {{end}}", bifrost)
            self.assertTrue(set(networks.split()) == {network}, "Only the internal network may remain during probes")
            deadline = time.monotonic() + 30
            while time.monotonic() < deadline:
                if status(9092, "/v1/models") == 401:
                    break
                time.sleep(0.25)
            else:
                self.fail("Real model-catalog guard readiness timed out")
            self.edge_probe("guard-ready/no-auth", {}, code=401)
            code, _, headers = request(self.backend, "/api/session/login", "POST", payload={
                "username": credentials["BIFROST_ADMIN_USERNAME"],
                "password": credentials["BIFROST_ADMIN_PASSWORD"],
            })
            self.assertEqual(code, 200, "Generated admin login status")
            cookie = SimpleCookie()
            for name, value in headers:
                if name.lower() == "set-cookie":
                    cookie.load(value)
            self.assertTrue("token" in cookie, "Admin login must issue a session")
            self.private_values.append(cookie["token"].value)
            self.admin = {"Cookie": "token=" + cookie["token"].value}
            self.assertEqual(len(self.api("/api/providers").get("providers", [])), 0)
            _, empty = self.virtual_key("no-providers-granted")
            retired_id, retired = self.virtual_key("revoked-with-no-providers")
            self.revoke(retired_id)
            invalid = {"Authorization": "Bearer sk-bf-" + secrets.token_urlsafe(32)}
            self.private_values.append(invalid["Authorization"][7:])
            for case, auth, code in (("absent", {}, 401), ("invalid", invalid, 403),
                                     ("revoked", retired, 403), ("no-grants", empty, 403),
                                     ("admin-cookie-only", self.admin, 401)):
                self.raw_probe("empty/" + case, auth, quirk="empty-auth-bypass")
                self.edge_probe("empty/" + case, auth, code=code)

            for port, (provider, models) in enumerate(PROVIDERS.items(), 9101):
                self.api("/api/providers", "POST", {
                    "provider": provider, "custom_provider_config": {"base_provider_type": "openai"},
                    # Named local-mock exception: allow private addresses solely
                    # for this loopback URL. No external network remains; exact
                    # stored grants and scoped identities are verified below.
                    # Removed with this fixture, production defaults untouched.
                    "network_config": {"base_url": f"http://127.0.0.1:{port}", "allow_private_network": True},
                })
                value = secrets.token_urlsafe(32)
                self.private_values.append(value)
                key = self.api(f"/api/providers/{provider}/keys", "POST", {
                    "name": provider + "-key", "value": value, "models": list(models), "weight": 1.0,
                })
                self.assertTrue(isinstance(key.get("id"), str), "Provider key resource ID")
                self.provider_keys[provider] = key["id"]
            self.assertEqual(len(self.api("/api/providers").get("providers", [])), 2)
            # An admin session authorizes management ONLY, not model inference.
            for name, auth in (("absent", {}), ("invalid", invalid), ("admin-cookie-only", self.admin)):
                self.raw_probe("configured/" + name, auth, code=401, quirk="denial-metadata")
            alpha_id, alpha = self.virtual_key("scope-alpha-one", (("isolation-alpha", ("alpha-one",)),))
            _, alpha_two = self.virtual_key("scope-alpha-two", (("isolation-alpha", ("alpha-two",)),))
            _, beta = self.virtual_key("scope-beta-one", (("isolation-beta", ("beta-one",)),))
            _, multi = self.virtual_key("scope-multi-provider", (("isolation-alpha", ("alpha-two",)),
                                                                ("isolation-beta", ("beta-one",))))
            scopes = (("alpha", alpha, ("isolation-alpha/alpha-one",)),
                      ("alpha-two", alpha_two, ("isolation-alpha/alpha-two",)),
                      ("beta", beta, ("isolation-beta/beta-one",)),
                      ("multi", multi, ("isolation-alpha/alpha-two", "isolation-beta/beta-one")))
            for name, auth, allowed in scopes:
                self.raw_probe("configured/" + name, auth, allowed, quirk="scoped-data-with-diagnostics")
                self.edge_probe("configured/" + name, auth, allowed)
            for name, auth, code in (("absent", {}, 401), ("invalid", invalid, 403),
                                     ("no-grants", empty, 403), ("already-revoked", retired, 403),
                                     ("admin-cookie-only", self.admin, 401)):
                self.edge_probe("configured/" + name, auth, code=code)
            # Any query is denied rather than delegated: known controls, arbitrary
            # fields, duplicate fields, percent-encoding and even a bare '?' form.
            for index, query in enumerate(("?", "?provider=isolation-beta", "?provider=isolation-alpha",
                    "?unfiltered=true", "?unfiltered=false", "?limit=1", "?offset=1", "?unknown=1",
                    "?provider=isolation-alpha&provider=isolation-beta", "?%75nfiltered=true",
                    "?token=" + beta["Authorization"][7:])):
                self.edge_probe("query/" + str(index), alpha, path="/v1/models" + query, code=400)
            for header in ("x-bf-vk", "x-api-key", "x-goog-api-key", "api-key"):
                alternative = {header: beta["Authorization"][7:]}
                self.raw_probe("header/" + header, alternative, ("isolation-beta/beta-one",),
                               quirk="scoped-data-with-diagnostics")
                self.edge_probe("header-only/" + header, alternative, code=401)
                self.edge_probe("conflicting/" + header, {**alpha, **alternative}, ("isolation-alpha/alpha-one",))
                self.edge_probe("invalid-plus-valid/" + header, {**invalid, **alternative}, code=403)
            direct = secrets.token_urlsafe(32)
            self.private_values.append(direct)
            self.edge_probe("direct-key-attempt", {**invalid, "x-bf-direct-key": "true", "x-api-key": direct}, code=403)
            self.edge_probe("cookie-attempt", {**invalid, **self.admin}, code=403)
            self.edge_probe("malformed-bearer",
                            {"Authorization": "Bearer " + direct, "x-bf-vk": beta["Authorization"][7:]}, code=401)
            self.revoke(alpha_id)
            self.raw_probe("configured/revoked", alpha, code=403, quirk="denial-metadata")
            self.edge_probe("configured/revoked", alpha, code=403)
            # Prove revocation/isolation, not a failed backend after the mutation.
            self.edge_probe("configured/unrevoked-control", beta, ("isolation-beta/beta-one",))
            self.assertFalse((data / "logs.db").exists(), "Request logging must remain disabled")


if __name__ == "__main__":
    unittest.main()