# Generated by Django 5.2.17 on 2026-09-08 20:20

import crm.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile_profilegrant_user_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')])),
                ('timezone', models.CharField(default='UTC', max_length=100, validators=[crm.models.validate_iana_timezone])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('trust', 'Trust'), ('foundation', 'Foundation')], default='person', max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('background', models.TextField(blank=True)),
                ('do_not_solicit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_contacts', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('evidence', models.TextField(blank=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='crm.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactEngagementSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_web_at', models.DateTimeField(blank=True, null=True)),
                ('event_count', models.PositiveBigIntegerField(default=0)),
                ('session_count', models.PositiveBigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='engagement_summary', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('postal', 'Postal')], max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(max_length=100)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_from', to='crm.contact')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_to', to='crm.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')])),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('acknowledgement_status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('gift', 'Gift'), ('refund', 'Refund')], default='gift', max_length=10)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='crm.appeal')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('original_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='crm.donation')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='crm.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appeal',
            name='default_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='crm.fund'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('meeting', 'Meeting'), ('sms', 'SMS'), ('letter', 'Letter'), ('social', 'Social'), ('internal_note', 'Internal note'), ('web', 'Web')], max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(blank=True, max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('team', 'Team'), ('restricted', 'Restricted')], default='team', max_length=20)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.appeal')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.donation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512, validators=[crm.models.validate_storage_key])),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='crm.interaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=320)),
                ('role', models.CharField(max_length=50)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interaction_participations', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='crm.interaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interaction_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MutationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('major_gift', 'Major gift'), ('grant', 'Grant'), ('sponsorship', 'Sponsorship')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('identified', 'Identified'), ('qualifying', 'Qualifying'), ('cultivating', 'Cultivating'), ('asked', 'Asked'), ('committed', 'Committed'), ('declined', 'Declined')], default='identified', max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')])),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.appeal')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.fund')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_opportunities', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='donation',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='crm.opportunity'),
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use a three-letter uppercase currency code.')])),
                ('pledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='crm.appeal')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='crm.fund')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='crm.opportunity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.pledge'),
        ),
        migrations.CreateModel(
            name='FundraisingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(max_length=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundraising_tasks', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fundraising_tasks', to='crm.donation')),
                ('originating_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_tasks', to='crm.interaction')),
                ('resulting_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resulted_tasks', to='crm.interaction')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fundraising_tasks', to='crm.opportunity')),
                ('pledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fundraising_tasks', to='crm.pledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='crm.pledge'),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=253)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_required', models.BooleanField(default=True)),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, default=dict, validators=[crm.models.validate_reference_changes])),
                ('acting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_acted', to='accounts.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='crm.charity')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['charity', '-created_at'], name='crm_auditre_charity_fed6d2_idx'), models.Index(fields=['charity', 'entity_type', 'entity_id', '-created_at'], name='crm_auditre_charity_c2f81b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['charity', '-created_at'], name='crm_contact_charity_308754_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['charity', 'display_name'], name='crm_contact_charity_1987c5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['charity', 'owner', 'is_active'], name='crm_contact_charity_dc0958_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['charity', '-created_at'], name='crm_consent_charity_e3a4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['charity', 'contact', '-occurred_at'], name='crm_consent_charity_9ad9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['charity', 'contact', 'channel', 'purpose', '-occurred_at'], name='crm_consent_charity_e66b23_idx'),
        ),
        migrations.AddIndex(
            model_name='contactengagementsummary',
            index=models.Index(fields=['charity', '-created_at'], name='crm_contact_charity_37b36c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmethod',
            index=models.Index(fields=['charity', '-created_at'], name='crm_contact_charity_509d16_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmethod',
            index=models.Index(fields=['charity', 'contact', 'kind'], name='crm_contact_charity_b9cfbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact', 'kind'), name='crm_primary_contact_method'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['charity', '-created_at'], name='crm_contact_charity_85fe72_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['charity', 'from_contact'], name='crm_contact_charity_f558f9_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['charity', 'to_contact'], name='crm_contact_charity_61c2d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_contact', models.F('to_contact')), _negated=True), name='crm_relationship_not_self'),
        ),
        migrations.AddConstraint(
            model_name='contactrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='crm_relationship_dates'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['charity', '-created_at'], name='crm_fund_charity_81265b_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['charity', '-created_at'], name='crm_appeal_charity_9b9b69_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['charity', 'status', 'start_date'], name='crm_appeal_charity_32c026_idx'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gte', 0)), name='crm_appeal_target_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='crm_appeal_dates'),
        ),
        migrations.AddIndex(
            model_name='interactionattachment',
            index=models.Index(fields=['charity', '-created_at'], name='crm_interac_charity_af8aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionparticipant',
            index=models.Index(fields=['charity', '-created_at'], name='crm_interac_charity_47ee03_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionparticipant',
            index=models.Index(fields=['charity', 'contact', 'interaction'], name='crm_interac_charity_39a8ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='interactionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', True), ('user__isnull', True), _connector='OR'), name='crm_participant_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='interactionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('user__isnull', False), models.Q(('name', ''), _negated=True), models.Q(('address', ''), _negated=True), _connector='OR'), name='crm_participant_has_identity'),
        ),
        migrations.AddIndex(
            model_name='mutationreceipt',
            index=models.Index(fields=['charity', '-created_at'], name='crm_mutatio_charity_a128bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mutationreceipt',
            constraint=models.UniqueConstraint(fields=('charity', 'acting_profile', 'key'), name='crm_mutation_receipt_unique'),
        ),
        migrations.AddConstraint(
            model_name='mutationreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('acting_profile__isnull', True)), fields=('charity', 'key'), name='crm_bootstrap_receipt_unique'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['charity', '-created_at'], name='crm_opportu_charity_06a271_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['charity', 'contact', '-created_at'], name='crm_opportu_charity_22f728_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['charity', 'owner', 'stage'], name='crm_opportu_charity_3405c0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['charity', 'stage', 'expected_date'], name='crm_opportu_charity_984c7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gte', 0)), name='crm_opportunity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['charity', '-created_at'], name='crm_pledge_charity_8f5377_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['charity', 'contact', '-pledged_at'], name='crm_pledge_charity_88e463_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['charity', 'status', 'due_date'], name='crm_pledge_charity_d262da_idx'),
        ),
        migrations.AddConstraint(
            model_name='pledge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='crm_pledge_positive'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['charity', '-created_at'], name='crm_interac_charity_379c41_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['charity', '-occurred_at'], name='crm_interac_charity_9e484a_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['charity', 'channel', '-occurred_at'], name='crm_interac_charity_d28ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['charity', 'thread_id', '-occurred_at'], name='crm_interac_charity_c4ca36_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('charity', 'source', 'external_id'), name='crm_interaction_external_unique'),
        ),
        migrations.AddIndex(
            model_name='fundraisingtask',
            index=models.Index(fields=['charity', '-created_at'], name='crm_fundrai_charity_3b4b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='fundraisingtask',
            index=models.Index(fields=['charity', 'contact', '-created_at'], name='crm_fundrai_charity_86e631_idx'),
        ),
        migrations.AddIndex(
            model_name='fundraisingtask',
            index=models.Index(fields=['charity', 'assigned_to', 'status', 'due_at'], name='crm_fundrai_charity_1373e6_idx'),
        ),
        migrations.AddIndex(
            model_name='fundraisingtask',
            index=models.Index(fields=['charity', 'status', 'due_at'], name='crm_fundrai_charity_5ae290_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundraisingtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='crm_task_completed_at'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['charity', '-created_at'], name='crm_donatio_charity_2c599c_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['charity', 'contact', '-received_at'], name='crm_donatio_charity_47af67_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['charity', '-received_at'], name='crm_donatio_charity_bd608a_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['charity', 'acknowledgement_status'], name='crm_donatio_charity_b38bed_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='crm_donation_positive'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'gift'), ('original_donation__isnull', True)), models.Q(('kind', 'refund'), ('original_donation__isnull', False)), _connector='OR'), name='crm_donation_refund_original'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('original_donation', models.F('id')), _negated=True), name='crm_donation_not_self_refund'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('charity', 'source', 'external_id'), name='crm_donation_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acknowledgement_status', 'acknowledged'), _negated=True), ('acknowledged_at__isnull', False), _connector='OR'), name='crm_donation_acknowledged_at'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['charity', '-created_at'], name='crm_website_charity_a08be9_idx'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('charity', 'domain'), name='crm_website_domain_unique'),
        ),
    ]
